# Numpy

Numpy is a library which provides support for large, homogenous, multi-dimensional arrays and matrices.

In [3]:
import numpy as np

## Creating Arrays in Numpy

### Creating an Array from Python list

In [6]:
list1 = [10, 20, 30]
list1

[10, 20, 30]

In [7]:
array1 = np.array(list1)
array1

array([10, 20, 30])

In [9]:
# We can check the type of arr1, we can see it is an ndarray
# (or n-dimensional array)
# In this case we have only created a one dimensional array so far
type(array1)

numpy.ndarray

### Using arange() to create an Array

arange() takes creates and array from a range of numbers

In [11]:
array2 = np.arange(10, 20, 1) # (Start, Stop, Step-size)
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### Multi-dimensional Arrays

When we combine arrays together we can add dimensions. So two arrays together makes a 2d array. This creates a matrix for us to do matrix
operations on.

### Two dimensional Arrays

In [13]:
# creating a new list to join to first one
list2 = [40,50,60]

# join the lists together
list3 = [list1, list2]
list 

# create 2d array from the joined lists
array3 = np.array(list3)
array3

array([[10, 20, 30],
       [40, 50, 60]])

In [16]:
# Lets find the shape of the array
array3.shape # 2 arrays, 3 elements in each array

(2, 3)

### Three Dimensional Arrays

In [18]:
array3dim = np.array([[[1,2,3],[4,5,6]],[[5,6,7],[7,8,9]]])
array3dim

array([[[1, 2, 3],
        [4, 5, 6]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [19]:
array3dim.shape

(2, 2, 3)

### Using Arrays and Scalars

In [21]:
# we can perform simple multipliation to our ndarrays
# for example
array3dim * 3

array([[[ 3,  6,  9],
        [12, 15, 18]],

       [[15, 18, 21],
        [21, 24, 27]]])

In [22]:
# how is this differnt to list
list1 * 3

[10, 20, 30, 10, 20, 30, 10, 20, 30]

This is where numpy comes in, arrays and lits are treated differently. 

We can also multiply an arrat by another array using a "matrix operation"

In [23]:
# creating another array which has the same size as array1
array11 = np.array(list2)
array11

array([40, 50, 60])

In [24]:
# What will happen here
array1 * array11
# 

array([ 400, 1000, 1800])

In [26]:
# What is we try to mulplty array of different sizes
array1 * array2

ValueError: operands could not be broadcast together with shapes (3,) (10,) 

In [27]:
# But it is possible to multiply arrays of differ tdimensions but the same element size
array1 * array3dim

array([[[ 10,  40,  90],
        [ 40, 100, 180]],

       [[ 50, 120, 210],
        [ 70, 160, 270]]])

### Task
Create ndarrays of the following sizes:
1. One dimensional array with 12 elements (12,)
2. Two dimensional array size (3, 4)
3. Three dimensional array size (2, 5, 4)
4. Check the size of your ndarray to ensure it is correct

In [37]:
# One dimensional array with 12 elements (12,)
array_1d = np.arange(12)
array_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
array_1d.shape

(12,)

In [43]:
# Two dimensional array size (3, 4)
array_2d = np.arange(12).reshape(3,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
array_2d.shape

(3, 4)

In [45]:
# three dimensional array size (2, 5, 4)
array_3d = np.arange(40).reshape(2, 5, 4)
array_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]]])

In [46]:
array_3d.shape

(2, 5, 4)

# Accessing values in ndarrays

In [47]:
# How can we access the 60?
array3

array([[10, 20, 30],
       [40, 50, 60]])

In [56]:
# We can use indexing
print(array3[1][2])

60


In [57]:
print(array3[1, 2])

60


In [59]:
# if we wanted the bottom row in our ndarray we can do this
array3[0]

array([10, 20, 30])

In [63]:
# what if we just wanted the last row 30 60
array3[:,2]

array([30, 60])

### Statistical functions

There are many buit in statistical functions you can use:

In [65]:
# Sum of all values
print(array3.sum())

210


In [66]:
# Sum of all values columns wise
print(array3.sum(0))

[50 70 90]


In [67]:
# Sum of all values rows wise
print(array3.sum(1))

[ 60 150]


In [68]:
# find the mean
print(array3.mean())

35.0


In [69]:
# find the standard deviation
print(array3.std())

17.07825127659933


In [70]:
# find the varience
print(array3.var())

291.6666666666667


In [71]:
# find the min
print(array3.min())

10


In [72]:
# find the max
print(array3.max())

60


### Iterating through ndarrays

In [74]:
# 1d array
for x in array1:
    print(x)

10
20
30


In [75]:
# nd arrays nested loops
for dim in array3:
    for num in dim:
        print(num)

10
20
30
40
50
60


In [76]:
# alternative to nd arrays nested loops - ndtiter
# tends to be cleaner than nested loops in most cases(regarding ndarrays)
for x in np.nditer(array3):
    print(x)

10
20
30
40
50
60


### Saving and Loading in numpy

In [79]:
# to save an array to a file
np.save("new", array3)

In [78]:
np.load("new.npy")

array([[10, 20, 30],
       [40, 50, 60]])

In [81]:
# saving as .txt
np.savetxt("next.txt", array3, delimiter=",")

In [82]:
# load .txt
np.loadtxt("next.txt", delimiter=",")

array([[10., 20., 30.],
       [40., 50., 60.]])